import OpenAI from 'openai';
import { MarkingSchema, detectMissingCompulsorySentence } from './schema';
export const descriptors = `SPM EssayMark AI uses Bands 0,1,3,5 with 2/4 as intermediate. Part 1: C5 all relevant fully informed; CA5 straightforward ideas with task conventions reasonably appropriately; O5 simple connectors/cohesive devices appropriately; L5 basic vocabulary/simple grammar good control. Part 2: C5 all relevant; CA5 holds attention and communicates straightforward ideas appropriately; O5 generally well organised/coherent variety cohesive devices; L5 everyday vocabulary, simple and some complex forms good control. Part 3: C5 all relevant; CA5 genre conventions effectively hold attention/communicate with ease/fulfil purposes; O5 well organised/coherent variety cohesive devices good effect; L5 range incl less common lexis, simple/complex forms control and flexibility. Band 3 adequate but reader mostly informed; Band 1 limited with major omissions; Band 0 content impossible/irrelevant or no credit. Missing points primarily affect Content; genre/register CA; organisation O; language L.`;
export type MarkRequest={studentName:string;className?:string;examName?:string;part:'part1'|'part2'|'part3';genre:'email'|'guided_writing'|'story'|'review'|'report';question:string;expectedWordRange:string;compulsorySentence?:string;contentPoints:{id:string;requirement:string}[];acceptedInterpretations?:string;noAwardConditions?:string;essay:string};
export function wordCount(text:string){return (text.trim().match(/\b[\w'-]+\b/g)||[]).length}
export async function markEssay(input:MarkRequest){
 const key=process.env.OPENAI_API_KEY; if(!key) return heuristicMark(input);
 const client=new OpenAI({apiKey:key});
 const prompt=`Return only JSON matching the required schema. Never official mark; say AI-assisted provisional mark. Stage 1 evaluate every content point with quote evidence. Stage 2 award Content, Communicative Achievement, Organisation, Language 0-5; total=sum<=20. Safeguards: never invent content; accept valid alternatives; uncertainty review. ${descriptors}\nINPUT:${JSON.stringify(input)}`;
 for(let i=0;i<2;i++){ const r=await client.responses.create({model:'gpt-4.1-mini',input:prompt}); const text=r.output_text; const parsed=MarkingSchema.safeParse(JSON.parse(text)); if(parsed.success && parsed.data.taskFulfilment.length===input.contentPoints.length) return parsed.data; }
 return heuristicMark(input);
}
export function heuristicMark(input:MarkRequest){const wc=wordCount(input.essay); const missing=detectMissingCompulsorySentence(input.essay,input.compulsorySentence); const taskFulfilment=input.contentPoints.map(p=>{const hit=input.essay.toLowerCase().includes(p.requirement.split(/\s+/)[0]?.toLowerCase()||'');return {id:p.id,requirement:p.requirement,status: hit?'partially_addressed' as const:'not_addressed' as const,evidence:hit?input.essay.slice(0,80):'',explanation:hit?'Possible evidence found; teacher should verify.':'No clear evidence found in heuristic fallback.',confidence:.55}}); const content=Math.max(0, missing?2:Math.min(5,Math.round(taskFulfilment.filter(p=>p.status!=='not_addressed').length/Math.max(1,input.contentPoints.length)*5))); const scores={content:{score:content,bandDescriptor:'Heuristic provisional band; verify against descriptors.',justification:missing?'Compulsory sentence appears missing.':'Based on available task evidence.',evidence:taskFulfilment.map(t=>t.evidence).filter(Boolean)},communicativeAchievement:{score:3,bandDescriptor:'Adequate communicative achievement.',justification:'Fallback estimate pending AI/teacher review.',evidence:[]},organisation:{score:3,bandDescriptor:'Adequate organisation.',justification:'Fallback estimate pending AI/teacher review.',evidence:[]},language:{score:3,bandDescriptor:'Adequate language.',justification:'Fallback estimate pending AI/teacher review.',evidence:[]}}; const total=scores.content.score+scores.communicativeAchievement.score+scores.organisation.score+scores.language.score; return MarkingSchema.parse({submission:{studentName:input.studentName,part:input.part,genre:input.genre,wordCount:wc,expectedWordRange:input.expectedWordRange,wordRangeComment:`${wc} words; supporting evidence only.`},taskFulfilment,scores:{...scores,total},languageAnalysis:{strengths:['Meaning is generally understandable.'],grammarIssues:[],vocabularyComments:['Teacher verification required.'],sentenceStructureComments:['Review sentence variety.']},feedback:{studentFriendlyFeedback:'AI-assisted provisional mark – teacher verification required.',twoStrengths:['You attempted the task.','Some ideas are understandable.'],twoPriorities:['Address every required point.','Check grammar and organisation.'],improvedExample:input.essay.slice(0,220)},moderation:{confidence:missing?.5:.65,requiresTeacherReview:true,reviewReasons:[missing?'Compulsory sentence may be missing.':'Fallback marking used.']}})}
